# Spring LDAP CRUD Operations Binding and Unbinding Example

spring:
  ldap:

    # Spring LDAP
    #
    # In this example we use an embedded ldap server. When using a real one,
    # you can configure the settings here.
    #
     urls: ldap://46.44.189.210:389
     base: ou=people,dc=bonniebot
     username: cn=admin,dc=bonniebot
     password: secret

    # Embedded Spring LDAP
    # embedded:
     # base-dn: dc=memorynotfound,dc=com
     # credential:
     #   username: uid=admin
     #   password: secret
     # ldif: classpath:schema.ldif
     # port: 12345
     # validation:
     #   enabled: false